[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "fake_python_package"
authors = [{name = "David", email = "david@fakecompany.com"}]
dynamic = ["version", "description"]
